stages:
  - dev_build
  - dev_start
  - prod_build
  - prod_start

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
  SSH_SERVER_DEV: ssh -i ./key.pem -o StrictHostKeyChecking=no $DEV_SERVER
  SSH_SERVER_PROD: ssh -i ./key.pem -o StrictHostKeyChecking=no $PROD_SERVER

dev_build:
  stage: dev_build
  script:
    - echo $DEV_SERVER
    - cp $PEM_FILE ./key.pem && chmod 400 ./key.pem
    - echo $SSH_SERVER_DEV
    - $SSH_SERVER_DEV "cd $DEV_DIR && rm -rf node_modules"
    - $SSH_SERVER_DEV "cd $DEV_DIR && rm -rf .env.production"
    - $SSH_SERVER_DEV "cd $DEV_DIR && git pull && git checkout dev && git pull && yarn"
    - $SSH_SERVER_DEV "cd $DEV_DIR && cp .env.development .env.production && yarn build"
  only:
    - dev

dev_start:
  stage: dev_start
  script:
    - cp $PEM_FILE ./key.pem && chmod 400 ./key.pem
    - $SSH_SERVER_DEV "cd $DEV_DIR && pm2 restart next"
  only:
    - dev

prod_build:
  stage: prod_build
  script:
    - echo $PROD_SERVER
    - cp $PEM_FILE ./key.pem && chmod 400 ./key.pem
    - echo $SSH_SERVER_PROD
    - $SSH_SERVER_PROD "cd $PROD_DIR && rm -rf node_modules"
    - $SSH_SERVER_PROD "cd $PROD_DIR && git checkout master && git pull && yarn"
    - $SSH_SERVER_PROD "cd $PROD_DIR && yarn build"
  only:
    - master

prod_start:
  stage: prod_start
  script:
    - cp $PEM_FILE ./key.pem && chmod 400 ./key.pem
    - $SSH_SERVER_PROD "cd $PROD_DIR && pm2 restart app-web"
  only:
    - master            
